sudo: required
services:
  - docker
before_install:
  - docker pull surendrajat/twrp-builder:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-5.1.1-cleaned/omni_twrp-5.1.1_cleaned.tar.xz
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/T-rex2017/android_device_micromax_a096.git device/micromax/a096
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /root/twrp/
    source build/envsetup.sh && lunch omni_a096-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - cd out/target/product/a096
  - curl --uploade-file ./recovery.img ./https://transfer.sh/recovery.img

